services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: tester
    environment:
      - NODE_ENV=test
      - PORT=8080
    command: ["npm", "run", "test"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - .:/app
    depends_on:
      - test
    command: ["npm", "run", "start"]
